/* ---- Homework Problem 11.10 (**) -------------------------------------------
 *
 * A. Write an HTML form for the CGI adder function in Figure11.27. Your form
 * should include two text boxes that users fill in with the two numbers to be
 * added together. Your form should request content using the GET method.
 *
 * B.Check your work by using a real browser to request the form from Tiny,
 * submit the filled-in form to Tiny, and then display the dynamic content
 * generated by adder.
 *
 * ------------------------------------------------------------------------- */

